# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShixiUS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShixiUS
  
pod 'Bugly'
pod 'ReactiveSwift'
pod 'SnapKit'
pod 'RxCocoa'
pod 'RxSwift'
pod 'Alamofire'
pod 'Result'
pod 'Kingfisher'
  
  target 'ShixiUSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShixiUSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
